# Numpy Tutorial

In [2]:
import numpy as np

In [3]:
# np.arange()
data =  np.arange(15)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
data = data.reshape(5,3)  # data.reshape(row,col)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [5]:
data.shape # shape of data (row,col)

(5, 3)

In [6]:
data.ndim  # dimention of data

2

In [7]:
data.dtype.name   # data type of data

'int32'

In [8]:
data.itemsize # np_array any item (elemnts) size

4

In [9]:
data = np.arange(15,dtype='float64')
data.itemsize

8

In [10]:
data.size # size of the np_array

15

In [11]:
type(data)  # type of data

numpy.ndarray

In [12]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [13]:
type(np.array([1,2,3,4]))

numpy.ndarray

In [14]:
#a = np.array(1,2,3,4)    # WRONG
a = np.array([1,2,3,4])  # RIGHT

In [15]:
b = np.array([(1.5,2,3), (4,5,6)])  # 2 tuples are given in a single list
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [16]:
b.shape

(2, 3)

In [17]:
b = np.array([ [1,2,3], [4,5,6] ])
print(b.shape)
b

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.zeros((3,4)) # 3 rows 4 columns zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((2,3), dtype=np.float64) # data type float64 -> itemsize will be 8

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.empty( (2,3) ) ## uninitialized, output may vary

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.arange( 10, 30, 5 ) # array range 10 to 30 , 5-1 elements

array([10, 15, 20, 25])

In [22]:
np.arange( 0, 2, 0.3 )                 # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [23]:
np.linspace(0,2,5)  # equal distance 5 points b/t 0 to 2 

array([0. , 0.5, 1. , 1.5, 2. ])

In [24]:
from numpy import pi
x = np.linspace( 0, 2*pi, 100 ) 
data = np.sin(x)

In [25]:
a = np.arange(6)                         # 1D
b = np.arange(12).reshape(4,3)           # 2D  4 row 3 columns
c = np.arange(30).reshape(2,5,3)         # 3D  2->(5,3)
print("1D : \n",a)
print("2D : \n",b,end='\n\n')
print("3D : \n",c,end='\n\n') ##  2 , 2D array of (5,3)
##   reshape(12,5,8)  -> 12 , 2D array of (5,8)

1D : 
 [0 1 2 3 4 5]
2D : 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

3D : 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]



In [26]:
a = np.arange(5)
b = np.arange(5,10)
b+a

array([ 5,  7,  9, 11, 13])

In [27]:
a**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [28]:
a*b

array([ 0,  6, 14, 24, 36])

In [29]:
a<3  # return a list of True False

array([ True,  True,  True, False, False])

In [30]:
a[a<3] # True Values print

array([0, 1, 2])

In [31]:
print(a * b)                       # elementwise product
print(a @ b)                       # matrix product
print(a.dot(b))                    # another matrix product

[ 0  6 14 24 36]
80
80


In [32]:
np.random.random()  # return random value in range 0 to 1
np.random.random(10)  # return 10 random value in range 0 to 1

array([0.57604258, 0.46015973, 0.23442289, 0.70481436, 0.54956987,
       0.96791724, 0.18420776, 0.96228868, 0.07588552, 0.50808704])

In [33]:
b = np.arange(5,10)
a

array([0, 1, 2, 3, 4])

In [34]:
print(np.sqrt(a))
print(np.add(a, b))
print(a.min()) # minimum of the array
print(a.max()) # max value to the array
print(a.sum()) # sum of elements

[0.         1.         1.41421356 1.73205081 2.        ]
[ 5  7  9 11 13]
0
4
10


In [36]:
print(np.mean([1,2,3,4]))

print(np.median([1,2,3,4,5]))

np.std([1,4,5,3,2,21])

2.5
3.0


6.831300510639732

In [34]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
b.sum(axis=0)  # axis = 0 -> sum of each column

array([12, 15, 18, 21])

In [36]:
b.sum(axis=1)   # axis = 1 -> sum of each row

array([ 6, 22, 38])

In [37]:
b.cumsum(axis=0) # # cumulative sum along each row

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

### Numpy functions

In [38]:
# all, any, apply_along_axis, argmax, argmin, argsort, average, bincount,
# ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, 
# floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, 
#nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var,
#vdot, vectorize, where

In [39]:
a = np.arange(10)**3
a[2:6]

array([  8,  27,  64, 125], dtype=int32)

In [40]:
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [41]:
data = np.arange(30).reshape(5,2,3)
data  # 3D data

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

In [42]:
for row in data:
    print(row,end="\n\n")

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]

[[12 13 14]
 [15 16 17]]

[[18 19 20]
 [21 22 23]]

[[24 25 26]
 [27 28 29]]



In [43]:
data = data.reshape(5,6)
data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [44]:
data.T   # returns the array, transposed

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [45]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(6,10).reshape(2,2)

In [46]:
np.vstack((a,b)) # vertical stack -> shape must be same

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [47]:
np.hstack((a,b))  # Horizontal stack -> shape must be same

array([[1, 2, 6, 7],
       [3, 4, 8, 9]])

In [48]:
# https://docs.scipy.org/doc/numpy/user/quickstart.html
# documentation